# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DocumentConnector
                                 A QGIS plugin
 With this Plugin documents can be connected to objects. It is designed for sewer system inspection data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-03
        copyright            : (C) 2023 by Armin Matzl
        email                : arminmatzl@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DocumentConnector class from file DocumentConnector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .document_connector import DocumentConnector
    return DocumentConnector(iface)
